import './../css/main.scss'
import './../public/template.html'
import './../public/pages/profil.html'
// import './home.js'
import './photographer.js'
// import './media'
import './validateform.js'
// import './sort.js'
