import './../css/main.scss'
import './../public/template.html'
import './../public/pages/mimikeel.html'
import './home'
// import './validateform'
// import './sort'
// import './json'
// import './photographers.js'
// import './../public/assets/images/logo.png'
